bases:
- ../../../qmgrs/qm01

patchesStrategicMerge:
- ./qm.yaml
- ./mqsc.yaml
# Alternative mechanism for patching
patches:
- target:
    group: mq.ibm.com
    kind: QueueManager
  patch: |-
    - op: add
      path: /spec/queueManager/image
      value: cp.icr.io/cp/ibm-mqadvanced-server-integration:9.2.3.0-r1
    - op: replace
      path: /metadata/name
      value: qmdev01
      
#configMapGenerator:
#- name: mqsc.config
#  behavior: merge
#  files:
#  - alt.mqsc
