bases:
- ../../base
patchesStrategicMerge:
- qm.yaml

patches:
- target:
    group: mq.ibm.com
    kind: QueueManager
  patch: |-
    - op: add
      path: /spec/queueManager/image
      value: ibm-mqadvanced-server-integration:9.2.3.0-r1
